# Generated by Django 4.1 on 2022-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_rightanswerid_alter_question_quiz_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
